### PR TITLE
Fix for issue #10 with empty environment variables overriding valid config file

### PR DESCRIPTION
**Pull request by j-bennet**
This fixes issue #10.

In addition:
- fixed config tests (they were only passing because they were wrong).
- fixed failing rules tests.

### CODE REVIEW

**Comment by abh1nav** [comment]
@j-bennet LGTM. Thanks for fixing the tests! Could you make a copy of [this](https://github.com/abh1nav/gnippy/blob/master/CLA/cla_template.txt) and include it as a part of the PR? Once that's done, I'll get the changes merged and push it out via PyPI.

**Comment by j-bennet** [comment]
@abh1nav, CLA added.

**Comment by abh1nav** [comment]
Thanks!

**Comment by abh1nav** [comment]
Closes #10.

**Pull request merged**
