### PR TITLE
Option for backfill minutes

### PR DESCRIPTION
**Pull request by markunsworth**
Added optional backfill minutes value as per the GNIP 2.0 [documentation](http://support.gnip.com/apis/powertrack2.0/recovery.html#backfill-a-idbackfill-classtallnbspa)

### CODE REVIEW

**Comment by j-bennet** [comment]
@markunsworth Looks good to me, but you may want to verify that `backfillMinutes` is not already contained in provided `url` (that's actually where I put it, and I assume other people may).

**Comment by markunsworth** [comment]
Ah yes, thats a good point. Will do that now.

I'm tracking when I was last connected using the changes in #22 so I can reconnect with a value less than 5.

**Comment by markunsworth** [comment]
I'm thinking it should replace the value in the url if it exists. Do you agree?

**Comment by j-bennet** [comment]
@markunsworth Makes sense to me.

**Comment by markunsworth** [comment]
I've really screwed up this branch trying to rebase after that other pull request was merged, I'm so far down a rabbithole with it I may as well kill it and start again.

**Pull request closed without merging**
